/*
 
 Author: Daniel Binggeli
 

*/
#ifndef ENCODER_H
#define ENCODER_H

// This is a basic class for the operation of a rotary encoder
// there's a read method available to get the counted increments.
// the get method is called to read the events up and down, which are generated by turning
// the encoder knob by one increment.
// this class is designed for use as a singleton, with direct access to hardware registers
 
class Encoder
{
  public:
  Encoder();
  int read();
  void eventGet(char &up, char &down);
};

extern Encoder encoder;
#endif;
